"""Liste de slots Gamdom pour l'autocompletion /call."""

from __future__ import annotations

GAMDOM_SLOTS = [
    "Sweet Bonanza",
    "Gates of Olympus",
    "Wanted Dead or a Wild",
    "The Dog House Megaways",
    "Sugar Rush",
    "Fruit Party",
    "Fruit Party 2",
    "Starlight Princess",
    "Starlight Princess 1000",
    "Big Bass Bonanza",
    "Big Bass Splash",
    "Big Bass Amazon Xtreme",
    "Big Bass Halloween",
    "Big Bass Christmas Bash",
    "Chaos Crew",
    "Le Bandit",
    "Mental",
    "Dork Unit",
    "Dead Canary",
    "Rip City",
    "Tombstone RIP",
    "The Bowery Boys",
    "Pirots",
    "Pirots 3",
    "Annihilator",
    "Evil Goblins",
    "The Rave",
    "Fury of Odin Megaways",
    "Buffalo King Megaways",
    "Madame Destiny Megaways",
    "Extra Juicy Megaways",
    "Bonanza Megaways",
    "Rise of Merlin Megaways",
    "Cash Elevator",
    "Gold Party",
    "The Great Chicken Escape",
    "Fire Portals",
    "Book of Shadows",
    "Hand of Anubis",
    "Release the Kraken Megaways",
    "5 Lions Megaways",
    "Power of Thor Megaways",
    "Aztec Bonanza",
    "Mystic Chief",
    "Wild West Gold",
    "Wild West Gold Megaways",
    "Money Train 2",
    "Money Train 3",
    "San Quentin xWays",
    "Big Bamboo",
    "Sticky Piggy",
    "Razor Shark",
    "Bigger Bass Bonanza",
    "Bigger Bass Splash",
    "Bigger Bass Blizzard",
    "Book of Dead",
    "Legacy of Dead",
    "Reactoonz",
    "Reactoonz 2",
    "Jammin Jars",
    "Jammin Jars 2",
    "Money Cart 2",
    "Gladiator Legends",
    "Wanted Mega Ways",
    "Wolf Gold",
    "Moon Princess 100",
    "Moon Princess Trinity",
    "Ze Zeus",
    "Phoenix Forge",
    "Hades Inferno",
    "Mayan Stackways",
    "Aloha King Elvis",
    "Toshi Video Club",
    "Roman Legion Xtreme",
    "Immortal Ways Buffalo",
    "Big Heist",
    "Coins of Fortune",
    "Densho",
    "Shamrock Saints",
    "Dragon Hero",
    "Lucky New Year",
    "Santa's Great Gifts",
    "Stack'em",
    "Hot Fiesta",
    "Hot Fiesta Megaways",
    "John Hunter and the Book of Tut",
    "John Hunter and the Quest for Bermuda Riches",
    "Chicken Drop",
    "Bomb Bonanza",
    "Joker Bombs",
    "Power of Merlin Megaways",
    "Might of Ra",
    "Mammoth Gold Megaways",
    "Gems Bonanza",
    "Cursed Seas",
    "Punk Rocker 2",
    "Nine to Five",
    "Cash Crew",
    "Fire in the Hole 2",
    "Madame Destiny",
]

